#../bin/qc:./main.cpp ./*.h
#	g++ -g -O3 --std=c++11 ./main.cpp -Wall -lboost_filesystem -lboost_system -lz -o ../bin/qc
#
../bin/read:./read.cpp ./DecompressedFiles.h
	g++ --std=c++11 ./read.cpp -Wall -o ../bin/read
